options.none               = Nenhum
options.choose             = Selecione
options.change             = Alterar
options.cancel             = Cancelar
options.save               = Salvar
options.preview            = Preview

datagrid.button.insert     = Inserir
datagrid.button.delete     = Deletar Selecionados
datagrid.statusbar.listpg  = Listando %d de %d registros.
datagrid.statusbar.paging  = Página %d de %d
datagrid.statusbar.listing = Listando %d registros.

detail.form.header         = Detalhe de %s

input.validate.short       = Campo %s tem %d caracteres! Mínimo é %d!
input.validate.long        = Campo %s tem %d caracteres! Máximo é %d!
input.validate.empty       = Preencha %s!

input.validate.error.currency = %s está em formato de moeda inválido!
input.validate.error.date     = %s é uma data inválida!
input.validate.error.email    = %s está em formato de e-mail inválido!
input.validate.error.zip      = %s está em formato de CEP inválido!
input.validate.error.phone    = %s está em formato de telefone inválido!
input.validate.error.document = %s está em formato de documento inválido!
input.validate.error.number   = %s é um número inválido!
input.validate.error.credcard = %s é um cartão inválido!

upload.error.mindimension  = A imagem não tem dimensões suficientes para a área destinada! Tamanho mínimo de %d x %d!
upload.error.maxsize       = Arquivo muito grande. Tamanho máximo é %d Kb
upload.error.filedenied    = File not writtable (%s)
upload.error.folderdenied  = Server error. Upload directory is not writable.
upload.error.emptyfile     = File is empty
upload.error.type          = Tipo de arquivo não permitido. Extensões esperadas são $s.
upload.error.generic       = Não foi possivel salvar o arquivo.


calendar.month.1           = Janeiro
calendar.month.2           = Fevereiro
calendar.month.3           = Março
calendar.month.4           = Abril
calendar.month.5           = Maio
calendar.month.6           = Junho
calendar.month.7           = Julho
calendar.month.8           = Agosto
calendar.month.9           = Setembro
calendar.month.10          = Outubro
calendar.month.11          = Novembro
calendar.month.12          = Dezembro


